trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python src/data_processing.py
    python src/model.py
  displayName: 'Run data processing and model training'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'model'
    ArtifactName: 'model-artifact'
